### ISSUE TITLE
JSON.parse truncating json output

### ISSUE THREAD

**Issue by awesumnitz** [isc-projects/kea-anterius#17]
Hi 
It looks like JSON.parse in lib/api_service.js. cutting off requests with a content-length larger than 24,000 .
If it's any larger, we get the error

> SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/kea-anterius/lib/api_service.js:34:42)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at IncomingMessage.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Log:
[npm_debug.log](https://github.com/isc-projects/kea-anterius/files/2436202/npm_debug.log)

By adding the module JSONStream, we've been able to get around this issue and do requests with a content-length larger than 140,000.

FROM:
 lib/api_service.js Line 5
`var http = require('http');`

 lib/api_service.js Line 34
`res.on('data', function (body) {
                    // console.log('BODY: ' + body);
                    response_data = JSON.parse(body)[0];
                });`
TO 

 lib/api_service.js Line 5
`var http = require('http'), JSONStream = require('JSONStream');`

 lib/api_service.js Line 34
`res.on('data', function (body) {
                    // console.log('BODY: ' + body);
                    response_data = JSONStream.parse(body)[0];
                });`

**Comment by raybellis** [comment]
I think this is a duplicate of #12, caused by an incorrect assumption that the entire body is received within a single `.on('data', ...)` event.
