### ISSUE TITLE
Non-sequential subnet IDs are improperly handled

### ISSUE THREAD

**Issue by kevanbrown** [isc-projects/kea-anterius#19]
app.js lines 257-259:

```
for (var i = 1; i <= subnet_count; i++) {
	global.kea_server.total_leases += global.kea_stats['subnet[' + i + '].assigned-' + global.kea_server.addr_tag][0][0];
}
```

Kea Administrator Reference documentation:
https://jenkins.isc.org/job/Kea_doc/guide/kea-guide.html#ipv4-subnet-id

> If there are multiple subnets configured with auto-generated identifiers and one of them is removed, the subnet identifiers may be renumbered. For example: if there are four subnets and the third is removed the last subnet will be assigned the identifier that the third subnet had before removal. As a result, the leases stored in the lease database for subnet 3 are now associated with subnet 4, something that may have unexpected consequences. It is planned to implement a mechanism to preserve auto-generated subnet ids in a future version of Kea. However, the only remedy for this issue at present is to manually specify a unique identifier for each subnet. 

The statistics code above doesn't account for non-sequential subnet IDs.  This causes the code block to fail with the following error:

```
Error 1:  TypeError: Cannot read property '0' of undefined
    at /home/pi/kea-anterius/app.js:258:135
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by tomaszmrugalski** [comment]
This problem doesn't exist in Stork. Our test environment uses non-consecutive subnet-ids. Some are starting from one, others from 11 and yet another from 21. Take a look at that [Grafana screenshots](https://github.com/isc-projects/stork/) (need to scroll down quite a bit).
