### ISSUE TITLE
Issues with config backups

### ISSUE THREAD

**Issue by jdtinsley88** [isc-projects/kea-anterius#22]
Here is a snippet of an issue -   I am running Centos 7 and installed everything per the instructions.

POST /dhcp_config_snapshots - - ms - -
[WS] STATUS: Socket clients (1)
{ Error: ENOENT: no such file or directory, mkdir 'config_backups/dhcp4'
    at Object.fs.mkdirSync (fs.js:885:18)
    at /root/kea-anterius/routes/dhcp_config_snapshots.js:39:16
    at Layer.handle [as handle_request] (/root/kea-anterius/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/kea-anterius/node_modules/express/lib/router/route.js:137:13)
    at auth (/root/kea-anterius/lib/authorize.js:30:4)
    at Layer.handle [as handle_request] (/root/kea-anterius/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/kea-anterius/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/kea-anterius/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/kea-anterius/node_modules/express/lib/router/layer.js:95:5)
    at /root/kea-anterius/node_modules/express/lib/router/index.js:281:22
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'config_backups/dhcp4' }
[WS] STATUS: Socket clients (1)
[WS] STATUS: Socket clients (1)
[WS] STATUS: Socket clients (1)
POST /dhcp_config_snapshots - - ms - -

**Comment by atmillertime** [comment]
`cd kea-anterius`
`mkdir config_backups`
`mkdir config_backups/dhcp4`
`mkdir config_backups/dhcp6`
