### ISSUE TITLE
Error 2:  Error: Status Code : 426

### ISSUE THREAD

**Issue by breakiboy** [isc-projects/kea-anterius#23]
HI Guys, 

Im trying to run Anterius on Debian 8.11. On Startup we run in the fallowing trouble:

root@dhcp01:~/kea-anterius# npm start

> kea-anterius@0.0.0 start /root/kea-anterius
> node ./bin/www

Anterius Server> Bootup complete
Anterius Server> OUI Database Loaded
Error 2:  Error: Status Code : 426
    at ClientRequest.<anonymous> (/root/kea-anterius/lib/api_service.js:27:35)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:558:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)

Can anyone help me to fix this?

**Comment by Anthrino** [comment]
Hi @breakiboy , thank you for raising this concern.
Status code 426 is regarding an upgradation for HTTP protocol being used.
I believe this is just a warning, are you able to operate the Anterius interface on localhost:3000?
Please report back if this issue is completely blocking the dashboard functions.

**Comment by pizu** [comment]
i have this issue too and with this am not able to operate anterius and the kea dhcp in 1 server
