### ISSUE TITLE
Centos 7 Kea 1.4.0-P1 Buggy

### ISSUE THREAD

**Issue by jdtinsley88** [isc-projects/kea-anterius#24]
I am running version 1.4.0-P1 and anterius seems very buggy.

Dashboard stats update and work fine, but the rest of anterius is not functioning properly.  

Here is some output - 

 npm start

> kea-anterius@0.0.0 start /root/kea-anterius
> node ./bin/www

Anterius Server> Bootup complete
Anterius Server> OUI Database Loaded
undefined
GET /?v_ajax 200 102.419 ms - 6217
undefined
GET /?v_ajax 304 92.210 ms - -
undefined
GET /?v_ajax 304 86.890 ms - -
undefined
GET /?v_ajax 304 94.618 ms - -
undefined
GET /?v_ajax 304 91.409 ms - -
undefined
GET /?v_ajax 304 88.557 ms - -
undefined
GET /?v_ajax 200 85.977 ms - 6219
undefined
GET /?v_ajax 304 86.759 ms - -
undefined
GET /?v_ajax 200 89.158 ms - 6220
undefined
GET /?v_ajax 304 88.590 ms - -
[WS] STATUS: Socket clients (0)
undefined
GET /?v_ajax 304 87.503 ms - -
undefined
GET /?v_ajax 200 87.699 ms - 6217
undefined
GET /?v_ajax 200 89.380 ms - 6221
undefined
GET /?v_ajax 304 85.669 ms - -
undefined
GET / 200 87.452 ms - 20951
GET /stylesheets/style.css 200 7.080 ms - 1147
GET /assets/plugins/bootstrap-select/css/bootstrap-select.css 200 5.343 ms - 7095
GET /assets/plugins/bootstrap/css/bootstrap.css 200 5.228 ms - 146118
GET /assets/plugins/node-waves/waves.css 200 4.355 ms - 4563
GET /assets/plugins/animate-css/animate.css 200 3.406 ms - 72259
GET /assets/plugins/morris/morris.css 200 1.949 ms - 433
GET /assets/css/glass.css 404 2.240 ms - 9
GET /assets/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css 200 0.925 ms - 4063
GET /assets/css/style.css 200 1.014 ms - 206873
GET /assets/css/themes/theme-green.css 200 0.939 ms - 1277
GET /assets/plugins/jquery/jquery.min.js 200 4.054 ms - 97163
GET /assets/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js 200 6.391 ms - 4851
GET /assets/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js 200 4.877 ms - 16027
GET /images/kea_logo.png 200 4.995 ms - 16409
GET /assets/plugins/raphael/raphael.min.js 200 4.339 ms - 92516
GET /assets/plugins/morris/morris.min.js 200 0.849 ms - 35652
GET /assets/js/api-examples.js 404 0.641 ms - 9
GET /assets/js/anterius-core.js 200 0.850 ms - 12008
GET /assets/js/anterius-websockets.js 200 0.858 ms - 1763
GET /assets/plugins/bootstrap/js/bootstrap.js 200 0.921 ms - 68954
GET /assets/plugins/bootstrap-select/js/bootstrap-select.js 200 1.527 ms - 62661
GET /assets/plugins/jquery-slimscroll/jquery.slimscroll.js 200 2.811 ms - 16825
GET /assets/plugins/bootstrap-notify/bootstrap-notify.js 200 2.205 ms - 11649
GET /assets/plugins/node-waves/waves.js 200 1.865 ms - 18135
GET /assets/js/admin.js 200 2.055 ms - 15884
GET /assets/plugins/jquery-datatable/jquery.dataTables.js 200 5.200 ms - 447281
GET /assets/js/file-saver.js 200 2.592 ms - 2445
GET /assets/js/pjax.js 200 2.623 ms - 6633
GET /assets/css/materialize.css 200 0.785 ms - 12253
GET /images/bg1.jpg 200 0.924 ms - 70746
GET /assets/plugins/bootstrap/fonts/glyphicons-halflings-regular.eot? 200 6.601 ms - 20127
GET /images/favicon.ico 200 1.489 ms - 1150
undefined
GET /?v_ajax 304 86.472 ms - -
undefined
GET /?v_ajax 200 89.704 ms - 6220
undefined
GET /?v_ajax 200 87.777 ms - 6220
undefined
GET /?v_ajax 200 90.218 ms - 6217
undefined
GET /?v_ajax 200 88.414 ms - 6220
(node:22833) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'leases' of undefined
    at /root/kea-anterius/routes/nw_detail_info.js:191:42
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:22833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22833) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
undefined
GET /?v_ajax 304 90.097 ms - -
undefined
GET /?v_ajax 200 86.180 ms - 6217
[WS] STATUS: Socket clients (0)
undefined
GET /?v_ajax 200 89.515 ms - 6221
undefined
GET /?v_ajax 200 87.605 ms - 6220
undefined
GET /?v_ajax 304 87.720 ms - -
undefined
GET /?v_ajax 304 88.250 ms - -
undefined
GET /?v_ajax 200 86.016 ms - 6217
undefined
GET /?v_ajax 200 78.678 ms - 6220

**Comment by Anthrino** [comment]
Hi @jdtinsley88 , thank you for raising this issue.
Could you mention the scenario where you encountered the following output on the console, like any specific action or links that resulted in this behavior.
Kindly pull the latest version from the repo and test it again, I've been pushing some updates, do reply to this thread with further details if you're facing the same issue.
