### ISSUE TITLE
Subnet-id issue

### ISSUE THREAD

**Issue by Ron9DK** [isc-projects/kea-anterius#35]
When setting the subnet id it seems like I need to do it in a consecutive sequence which isn't convenient to our setup.

Even if we just jump one number we get the error:
```
Error 1:  TypeError: Cannot read property '0' of undefined
    at /root/kea-anterius/app.js:271:131
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```
Is this behaviour to be expected? I consider this a bug and it would be really great with a fix so we would be able to have id's in different sequence ranges.

Regards
Ronni

**Comment by tomaszmrugalski** [comment]
Hey @Ron9DK 

Anterius is an abandoned project. It was a project developed by a single person as part of now concluded 3 months long GSOC project. Please take a look at [Stork](https://github.com/isc-projects/stork) instead. It's being actively maintained by a group of engineers. Stork allows non-consecutive subnet-ids and also supports multiple Kea instances and many other things that Anterius doesn't.
