### ISSUE TITLE
CentOS 7.5 failed to start npm 

### ISSUE THREAD

**Issue by satishdotpatel** [isc-projects/kea-anterius#36]
Trying to install this application on CentOS 7.5 and getting following error what am i missing here? 

Can you create small document for CentOS 7.5? 

```
[root@kea-server kea-anterius]# sudo npm start

> kea-anterius@0.0.0 start /root/kea-anterius
> node ./bin/www

Anterius Server> Bootup complete
Request Error: connect ECONNREFUSED 127.0.0.1:8010
Request Error: connect ECONNREFUSED 127.0.0.1:8010
Request Error: connect ECONNREFUSED 127.0.0.1:8010
Error 2:  { Error: connect ECONNREFUSED 127.0.0.1:8010
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8010 }
Request Error: connect ECONNREFUSED 127.0.0.1:8010
Error 1:  { Error: connect ECONNREFUSED 127.0.0.1:8010
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8010 }
Anterius Server> OUI Database Loaded
```

**Comment by satishdotpatel** [comment]
Look like even after GUI is working but when i trying to got to home page i get pop up window 

Saying "unable to connect selected server" 
Validate your CA setting. 

On nodejs i am getting following error 

GET /assets/plugins/bootstrap/fonts/glyphicons-halflings-regular.woff2 304 2.451 ms - -
Error 1:  TypeError: Cannot read property '0' of undefined
    at /root/kea-anterius/app.js:271:131
    at process._tickCallback (internal/process/next_tick.js:109:7)
Error 1:  TypeError: Cannot read property '0' of undefined
    at /root/kea-anterius/app.js:271:131
    at process._tickCallback (internal/process/next_tick.js:109:7)
Error 1:  TypeError: Cannot read property '0' of undefined
    at /root/kea-anterius/app.js:271:131
    at process._tickCallback (internal/process/next_tick.js:109:7)
[WS] ping from (IqrZ3IKAuohhSnnVJxg8hQ==)
[WS] received pong from (IqrZ3IKAuohhSnnVJxg8hQ==)
Error 1:  TypeError: Cannot read property '0' of undefined
    at /root/kea-anterius/app.js:271:131
    at process._tickCallback (internal/process/next_tick.js:109:7)
Error 1:  TypeError: Cannot read property '0' of undefined
    at /root/kea-anterius/app.js:271:131
    at process._tickCallback (internal/process/next_tick.js:109:7)
[WS] ping from (IqrZ3IKAuohhSnnVJxg8hQ==)
[WS] received pong from (IqrZ3IKAuohhSnnVJxg8hQ==)

**Comment by pizu** [comment]
I have the same issue,

issue is between kea control agent and the gui somehow are conflicting..

**Comment by tomaszmrugalski** [comment]
Anterius is an abandoned project. It was a project developed by a single person as part of now concluded 3 months long GSOC project. Please take a look at [Stork](https://github.com/isc-projects/stork) instead. It's being actively maintained by a group of engineers.
